"""Quantuum Blueprint generator.

Ported from blueprint.ts — buildBlueprint must produce CHARACTER-EXACT output
matching the TypeScript implementation. Consumes the already-ported astrology
modules; reproduces the exact markdown line sequence, literals, emoji, tables,
and number formatting.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from datetime import datetime, timedelta, timezone
from typing import Any
from zoneinfo import ZoneInfo

from quantuum.astrology.util import to_fixed

# ---------------------------------------------------------------------------
# Input
# ---------------------------------------------------------------------------


@dataclass
class BlueprintInput:
    full_name: str
    birth_date: str  # YYYY-MM-DD
    birth_time: str  # HH:MM (24h, local time)
    birth_place: str | None
    latitude: float
    longitude: float
    timezone: str  # IANA name e.g. "Europe/Moscow", or "+03:00" offset
    for_year: int | None = None


# ---------------------------------------------------------------------------
# Timezone / instant handling
# ---------------------------------------------------------------------------

EPOCH = datetime(1970, 1, 1, tzinfo=timezone.utc)


def parse_birth_instant(inp: BlueprintInput) -> datetime:
    """Mirror blueprint.ts parseBirthInstant — returns a tz-aware UTC datetime."""
    stamp = f"{inp.birth_date}T{inp.birth_time}:00"
    if re.fullmatch(r"[+-]\d{2}:\d{2}", inp.timezone):
        return datetime.fromisoformat(f"{stamp}{inp.timezone}").astimezone(timezone.utc)
    naive = datetime.fromisoformat(stamp)
    return naive.replace(tzinfo=ZoneInfo(inp.timezone)).astimezone(timezone.utc)


def to_iso_z(ms: int) -> str:
    """JS Date.toISOString() from an integer epoch-ms value."""
    dt = EPOCH + timedelta(milliseconds=ms)
    return dt.strftime("%Y-%m-%dT%H:%M:%S.") + f"{dt.microsecond // 1000:03d}Z"


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def _render_header(inp: BlueprintInput, ctx) -> str:
    lines: list[str] = []

    def push(s: str) -> None:
        lines.append(s)

    push(f"# Quantuum Blueprint — {inp.full_name}")
    push("")
    push(f"**Birth date:** {inp.birth_date}  ")
    push(f"**Birth time:** {inp.birth_time} ({inp.timezone})  ")
    push(
        f"**Birth place:** {inp.birth_place if inp.birth_place is not None else '—'} "
        f"({to_fixed(inp.latitude, 4)}°, {to_fixed(inp.longitude, 4)}°)  "
    )
    push(f"**UTC instant:** {to_iso_z(ctx.birth_ms)}  ")
    push(f"**Personal-year target:** {ctx.for_year}  ")
    push("**Quantuum Matrix framework:** 35-dimensional  ")
    push("")
    push("---")
    push("")
    return "\n".join(lines)


def _render_footer() -> str:
    return "\n".join([
        "---",
        "",
        "_Generated by quantuum-blueprint calculator — every number above is computed "
        "from the birth data above; nothing is sourced from an LLM._",
        "",
    ])


def build_blueprint(inp: BlueprintInput) -> str:
    from quantuum.astrology.sections import (
        BLUEPRINT_SECTION_ORDER,
        SECTION_BUILDERS,
        build_blueprint_context,
    )

    ctx = build_blueprint_context(inp)
    parts = [_render_header(inp, ctx)]
    for kind in BLUEPRINT_SECTION_ORDER:
        parts.append(SECTION_BUILDERS[kind](inp, ctx))
    parts.append(_render_footer())
    return "\n".join(parts)


# ---------------------------------------------------------------------------
# NatalProfile adapter
# ---------------------------------------------------------------------------


def from_natal_profile(profile: Any) -> BlueprintInput:
    """Build a BlueprintInput from a duck-typed NatalProfile-like object.

    Avoids a hard import of the DB layer so this module stays importable
    without it.
    """
    return BlueprintInput(
        full_name=profile.full_name,
        birth_date=profile.birth_date.isoformat(),
        birth_time=profile.birth_time.strftime("%H:%M"),
        birth_place=profile.birth_place,
        latitude=float(profile.latitude),
        longitude=float(profile.longitude),
        timezone=profile.timezone,
        for_year=profile.for_year,
    )
