"""tenancy: tenant_bots, tenant_roles, tenant fields

Revision ID: 333649f38ecf
Revises: 09815c38a9b7
Create Date: 2026-05-20 18:25:58.640280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '333649f38ecf'
down_revision: Union[str, Sequence[str], None] = '09815c38a9b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_bots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('bot_telegram_id', sa.Integer(), nullable=True),
    sa.Column('bot_username', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('bot_token_enc', sa.LargeBinary(), nullable=False),
    sa.Column('transport', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('webhook_secret_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_bots_bot_telegram_id'), 'tenant_bots', ['bot_telegram_id'], unique=True)
    op.create_index(op.f('ix_tenant_bots_tenant_id'), 'tenant_bots', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_tenant_bots_webhook_secret_path'), 'tenant_bots', ['webhook_secret_path'], unique=True)
    op.create_table('tenant_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('granted_by_account_id', sa.Integer(), nullable=True),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['granted_by_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'account_id', 'role')
    )
    op.create_index(op.f('ix_tenant_roles_account_id'), 'tenant_roles', ['account_id'], unique=False)
    op.create_index(op.f('ix_tenant_roles_tenant_id'), 'tenant_roles', ['tenant_id'], unique=False)
    op.add_column('tenants', sa.Column('tier', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='basic'))
    op.add_column('tenants', sa.Column('is_platform', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('tenants', sa.Column('primary_owner_account_id', sa.Integer(), nullable=True))
    op.add_column('tenants', sa.Column('owner_tg_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('tenants', sa.Column('owner_chat_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_foreign_key('fk_tenants_primary_owner_account_id', 'tenants', 'accounts', ['primary_owner_account_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_tenants_primary_owner_account_id', 'tenants', type_='foreignkey')
    op.drop_column('tenants', 'owner_chat_id')
    op.drop_column('tenants', 'owner_tg_id')
    op.drop_column('tenants', 'primary_owner_account_id')
    op.drop_column('tenants', 'is_platform')
    op.drop_column('tenants', 'tier')
    op.drop_index(op.f('ix_tenant_roles_tenant_id'), table_name='tenant_roles')
    op.drop_index(op.f('ix_tenant_roles_account_id'), table_name='tenant_roles')
    op.drop_table('tenant_roles')
    op.drop_index(op.f('ix_tenant_bots_webhook_secret_path'), table_name='tenant_bots')
    op.drop_index(op.f('ix_tenant_bots_tenant_id'), table_name='tenant_bots')
    op.drop_index(op.f('ix_tenant_bots_bot_telegram_id'), table_name='tenant_bots')
    op.drop_table('tenant_bots')
    # ### end Alembic commands ###
